Repository GSG-K3/books-for-everyone, pull requests merged in 2020-06, with the labels that each got.

#4 upload project files #1
  .env
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
Labels: change-request

#13 create header component & add img file
  src/App.js
  src/Images/Searching-512.png
  src/Images/books-cartoon1.png
  src/Images/smalle-books.png
  src/components/Common/Header/Header.js
  src/components/Common/Header/header.css
  src/components/Common/Search/Search.js
  src/components/Common/Search/search.css
Labels: approved

#15 delete files create search function
  .gitignore
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/App.test.js
  src/components/Common/Search/Search.js
  src/components/Common/Search/search.css
  src/components/Layout/SearchResult/SearchResult.js
Labels: in-progress
